services:
  - type: web
    name: flask-rag-app
    env: python
    region: oregon        # or choose your region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: CERABRAS_API_KEY
        sync: false
